stages:
  - docker-build
  - deploy

docker-build:
  stage: docker-build
  only:
    - master
    - main
  image: docker:stable
  services:
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy:
  stage: deploy
  only:
    - master
    - main
  needs: ["docker-build"]
  image: kroniak/ssh-client
  before_script:
    - echo "deploying app"
  script:
    - chmod 400 $SSH_PRIVATE_KEY
    - ssh -o StrictHostKeyChecking=no -p 2222 -i $SSH_PRIVATE_KEY root@$SERVER "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh -o StrictHostKeyChecking=no -p 2222 -i $SSH_PRIVATE_KEY root@$SERVER "docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - ssh -o StrictHostKeyChecking=no -p 2222 -i $SSH_PRIVATE_KEY root@$SERVER "docker rm -f vtesdecks-front || true"
    - ssh -o StrictHostKeyChecking=no -p 2222 -i $SSH_PRIVATE_KEY root@$SERVER "docker run --name vtesdecks-front --restart unless-stopped --network internal -d $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - ssh -o StrictHostKeyChecking=no -p 2222 -i $SSH_PRIVATE_KEY root@$SERVER "docker logout"
